### ISSUE TITLE
[FEATURE] [Backend] Unfollow someone on Twitter

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#14]
Create a new route /unfollow

This endpoint will accept one param from the request

targetUserId- ( id of the user to which we want to unfollow)

Don't forget to get the `refreshClient` from the getRefreshClient functions first.
use try catch to send responses and errors to the client side.

Resources that can help:-
https://github.com/plhery/node-twitter-api-v2/blob/HEAD/doc/v2.md#unfollow-someone

**Comment by dhruvdabhi101** [comment]
I would like to contribute

**Comment by sanyamjain04** [comment]
hi @dhruvdabhi101, 
you can see the `follow` route in the backend which can help you in creating `unfollow` route also.
it's mostly the same code but I think we have to change v2 method from  `follow ` to `unfollow`. 
feel free to ask any questions.

**Comment by dhruvdabhi101** [comment]
hello @sanyamjain04 
I'm getting some errors while authenticating on Twitter.
Here are some screenshots of that.
<img width="853" alt="Screenshot 2022-10-21 at 6 54 46 PM" src="https://user-images.githubusercontent.com/91935072/197207552-2200d8d4-27f7-49de-a5ba-14b8ab709402.png">
<img width="1133" alt="Screenshot 2022-10-21 at 6 55 00 PM" src="https://user-images.githubusercontent.com/91935072/197208075-73ff3ae9-4d37-4e28-8749-c35e49b3e612.png">

Can you help me with that ?

**Comment by dhruvdabhi101** [comment]
okay.. understood. I haven't created one row. I just have created only tables and columns. Thank you sir for guidance.

**Comment by sanyamjain04** [comment]
I am not sir 😅😅 brother.

**Comment by dhruvdabhi101** [comment]
> I am not sir 😅😅 brother.

Okay.. Thank you Brother.😅
