### ISSUE TITLE
[FEATURE] [Backend] Create userId route

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#15]
Create a new route /userid

This endpoint will accept one param from the request

username- ( username of the user )

this endpoint doesn't require `refreshClient` , we can use `readTwitterClient` from config.js
e.g - `const data = await readTwitterClient.v2.userByUsername(username);`

we have to send the userId and name to the client 

use try catch to send responses and errors to the client side.

Resources that can help:-
https://github.com/plhery/node-twitter-api-v2/blob/HEAD/doc/v2.md#single-user-by-username

**Comment by dhruvdabhi101** [comment]
I want to contribute to this issue.

**Comment by dhruvdabhi101** [comment]
can you please label this issue hacktoberfest if it is possible ?
