### ISSUE TITLE
[FEATURE] [Backend] Bookmark a Tweet

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#26]
Create a new route /bookmark

This endpoint will accept one param from the request
tweetId- ( id of the tweet to which we want to bookmark)

Don't forget to add the getRefreshClient functions first.
use try catch to send responses and errors to the client side.

Resources that can help:-
https://github.com/plhery/node-twitter-api-v2/blob/HEAD/doc/v2.md#bookmark-a-tweet

**Comment by imThiyagu** [comment]
I would like to work on this as well :)

**Comment by imThiyagu** [comment]
once we are closed with open PR's , I ll raise this to avoid conflicts

**Comment by dhruvdabhi101** [comment]
I would like to contribute to this issue

**Comment by sanyamjain04** [comment]
@imThiyagu Can we please solve one issue at one time?  This will encourage other contributors to contribute to this repo.

**Comment by dhruvdabhi101** [comment]
I have created PR can you please review it before 1st Nov ?
