### ISSUE TITLE
[FEATURE] [Frontend] Reply to a Tweet

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#4]
Create a new component `Reply.jsx`.

In that component Create -
1. Textarea with max 280 characters length - (required fields)
2. A Input type number for tweetId - (required fields)
3. A button with the name `Reply Tweet` with onClick `postReply` function 
4. Button Loading ( you can implement the same used in `Tweet.jsx` )

when creating postReply function for the button, make sure to handle empty inputs (Tweet Id and Reply Text ) also and show respective warnings using react toast notifications.

Add the styles to these components too. Styles should be the same as our existing styles.

Fell free to ask any questions / help.

**Comment by Shivam164** [comment]
Hey @sanyamjain04, I would like to work on this issue. Please assign this to me.

**Comment by sanyamjain04** [comment]
Hey @Shivam164 This video will give you an idea of Kubetweet's current features and UI of the Project:-
https://www.loom.com/share/de4b32c6295e4628a7b66fce2b227c16

We want the Reply feature to be like :
1. user will enter the tweet id in the tweetId input  
2. he can preview the tweet first by clicking on the preview button  ( you can use the same code used in retweet component to implement preview functionality ) 
3. user can click on the button `Reply to Tweet` and loading animation will show.

please add the screenshot of the Reply component when creating a PR.
If you have any questions, feel free to ask 🙂

**Comment by Shivam164** [comment]
Hey @sanyamjain04 I am not sure, what I am suppose to enter in the column of these table => https://user-images.githubusercontent.com/107163858/193412105-07ee5c5c-ba7f-4946-8cc8-8a207688d747.png

**Comment by sanyamjain04** [comment]
@Shivam164  just create 1 row in each table (tokens and states) and enter the id = 1 and you can enter any random word to the other columns because after authorization we will update these values.

**Comment by Shivam164** [comment]
Okay got it, thanks @sanyamjain04

**Comment by sanyamjain04** [comment]
@Shivam164 Any Updates?
