### ISSUE TITLE
[FEATURE] [Frontend] Follow someone on Twitter

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#8]
Create a new component Follow.jsx.

In this component Create -

1. A Input type text for User Id- (required field) 
2. A preview button 
3. A button with the name `Follow User`with onClick `followUser` function
4. A button with the name `Unfollow User`with onClick `unfollowUser` function 
5. Button Loading ( you can implement the same used in Retweet.jsx )

for idea it will look like Retweet component but name of elements and functions will change 
![image](https://user-images.githubusercontent.com/107163858/196868798-995618b5-1573-41a1-a6cb-c2936cdd76a2.png)

when creating followUser function for the button, make sure to handle empty inputs (User Id ) and show `Please enter valid UserId` warnings using react toast notifications.

Add the styles to these components too. Styles should be the same as our existing styles.

#### Want to do more ?
if you know the backend ( by adding the express `/follow` and `/unfollow` route ) too then you can try yourself to write the code ( API calls ) inside the functions otherwise Don't worry Someone else can write the function code, you can create the frontend  UI.

**Comment by KlausMikhaelson** [comment]
Hey @sanyamjain04 is this issue open to contribute or are you working on it ?

**Comment by sanyamjain04** [comment]
Yes, @KlausMikhaelson , This issue is open for contribution.

**Comment by sanyamjain04** [comment]
@KlausMikhaelson Any updates?

**Comment by KlausMikhaelson** [comment]
Hey @sanyamjain04 just saw the email ,my bad, will start working on it !

**Comment by sanyamjain04** [comment]
@KlausMikhaelson  Don't worry. I understand you were busy. It has been more than 1 week. So I completed the issue you can work on other issues if you want to.

**Comment by KlausMikhaelson** [comment]
@sanyamjain04 ooo my bad, will look for another one
