### ISSUE TITLE
[FEATURE] [Backend] Follow someone on Twitter

### ISSUE THREAD

**Issue by sanyamjain04** [kubesimplify/kubetweet#9]
Create a new route /follow

This endpoint will accept one param from the request
1. userId- ( id of the user to which we want to follow)

Don't forget to add the getRefreshClient functions first.
use try catch to send responses and errors to the client side.

Resources that can help:-
https://github.com/plhery/node-twitter-api-v2/blob/HEAD/doc/v2.md#follow-someone

**Comment by yash-gulatii** [comment]
Hey @sanyamjain04 can you assign me on this issue?
